server:
  port: 8090

spring:
  application:
    name: ms-auth
  datasource:
    url: jdbc:mysql://db-users:3306/users_db?createDatabaseIfNotExist=true&allowPublicKeyRetrieval=true&useSSL=false
    username: camilo
    password: mypassword
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

eureka:
  client:
    service-url:
      defaultZone: http://ms-discovery:8761/eureka/

security:
  jwt:
    secret-key: gk++rNiUx83bQVFKEMbRwPryle40/GIA1errK2vsSjs=
    token-expiration: 600000
