server:
  port: 8080

spring:
  application:
    name: ms-gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      routes:
        - id: ms-auth-route
          uri: http://host.docker.internal:8090
          predicates:
            - Path=/ms-auth/**
        - id: ms-users-route
          uri: http://host.docker.internal:8081
          predicates:
            - Path=/ms-users/**
        - id: ms-products-route
          uri: http://host.docker.internal:8082
          predicates:
            - Path=/ms-products/**

eureka:
  client:
    service-url:
      defaultZone: http://ms-discovery:8761/eureka/

security:
  jwt:
    secret-key: gk++rNiUx83bQVFKEMbRwPryle40/GIA1errK2vsSjs=
    token-expiration: 600000