server:
  port: 8080

spring:
  application:
    name: ms-gateway
  cloud:
    gateway:
      routes:
        - id: ms-auth
          uri: http://ms-auth:8090
          predicates:
            - Path=/ms-auth/**
          filters:
            - StripPrefix=1
        - id: ms-users
          uri: http://ms-users:8081
          predicates:
            - Path=/ms-users/**
          filters:
            - StripPrefix=1
        - id: ms-products
          uri: http://ms-products:8082
          predicates:
            - Path=/ms-products/**
          filters:
            - StripPrefix=1

security:
  jwt:
    secret-key: gk++rNiUx83bQVFKEMbRwPryle40/GIA1errK2vsSjs=
    token-expiration: 600000